import { PlantationData } from "./types";

// Realistic demo dataset modelled on a Ghanaian agri-business.
export const seedData: PlantationData = {
  farms: [
    {
      id: "farm-1",
      name: "Asankrangwa Estate",
      location: "Asankrangwa, Wassa Amenfi",
      region: "Western",
      areaHectares: 240,
      soilType: "Forest Ochrosol",
      latitude: 5.811,
      longitude: -2.428,
      establishedYear: 2014,
      notes: "Flagship cocoa and oil-palm estate.",
    },
    {
      id: "farm-2",
      name: "Techiman North Block",
      location: "Techiman, Bono East",
      region: "Bono East",
      areaHectares: 160,
      soilType: "Savanna Ochrosol",
      latitude: 7.583,
      longitude: -1.939,
      establishedYear: 2018,
      notes: "Maize, cassava and vegetable rotation.",
    },
    {
      id: "farm-3",
      name: "Keta Lagoon Gardens",
      location: "Keta, Volta",
      region: "Volta",
      areaHectares: 85,
      soilType: "Sandy Loam",
      latitude: 5.917,
      longitude: 0.987,
      establishedYear: 2021,
      notes: "Irrigated shallots and chilli.",
    },
  ],
  crops: [
    { id: "crop-1", farmId: "farm-1", name: "Cocoa", variety: "CRIG Hybrid", stage: "fruiting", areaHectares: 120, plantedDate: "2023-04-12", expectedHarvestDate: "2026-09-30", expectedYieldTons: 78, healthScore: 88 },
    { id: "crop-2", farmId: "farm-1", name: "Oil Palm", variety: "Tenera", stage: "harvest", areaHectares: 90, plantedDate: "2019-06-01", expectedHarvestDate: "2026-07-15", expectedYieldTons: 1450, healthScore: 92 },
    { id: "crop-3", farmId: "farm-2", name: "Maize", variety: "Obatanpa", stage: "vegetative", areaHectares: 70, plantedDate: "2026-04-02", expectedHarvestDate: "2026-08-10", expectedYieldTons: 210, healthScore: 75 },
    { id: "crop-4", farmId: "farm-2", name: "Cassava", variety: "Ampong", stage: "flowering", areaHectares: 60, plantedDate: "2025-11-20", expectedHarvestDate: "2026-11-20", expectedYieldTons: 540, healthScore: 81 },
    { id: "crop-5", farmId: "farm-3", name: "Shallots", variety: "Anloga Local", stage: "germination", areaHectares: 35, plantedDate: "2026-05-30", expectedHarvestDate: "2026-08-28", expectedYieldTons: 290, healthScore: 69 },
  ],
  workers: [
    { id: "wk-1", name: "Kwame Mensah", role: "Farm Manager", phone: "+233 24 111 2233", dailyRate: 180, joinedDate: "2016-02-01", status: "active" },
    { id: "wk-2", name: "Akosua Boateng", role: "Agronomist", phone: "+233 20 445 6677", dailyRate: 150, joinedDate: "2019-08-15", status: "active" },
    { id: "wk-3", name: "Yaw Darko", role: "Field Supervisor", phone: "+233 27 889 0011", dailyRate: 110, joinedDate: "2020-01-10", status: "active" },
    { id: "wk-4", name: "Ama Owusu", role: "Harvest Crew", phone: "+233 55 223 4455", dailyRate: 70, joinedDate: "2022-03-22", status: "active" },
    { id: "wk-5", name: "Kofi Asante", role: "Irrigation Tech", phone: "+233 24 776 5544", dailyRate: 95, joinedDate: "2021-09-05", status: "inactive" },
  ],
  attendance: [],
  inventory: [
    { id: "inv-1", name: "Cocoa Seedlings", category: "seed", quantity: 1200, unit: "units", reorderLevel: 500, unitCost: 3.5, supplier: "COCOBOD Nursery" },
    { id: "inv-2", name: "NPK 15-15-15", category: "fertilizer", quantity: 18, unit: "bags(50kg)", reorderLevel: 25, unitCost: 320, supplier: "Yara Ghana" },
    { id: "inv-3", name: "Glyphosate", category: "pesticide", quantity: 60, unit: "litres", reorderLevel: 30, unitCost: 45, supplier: "Agrimat Ltd" },
    { id: "inv-4", name: "Knapsack Sprayers", category: "equipment", quantity: 14, unit: "units", reorderLevel: 5, unitCost: 240, supplier: "Farmtools GH" },
    { id: "inv-5", name: "Diesel", category: "fuel", quantity: 210, unit: "litres", reorderLevel: 150, unitCost: 14.2, supplier: "GOIL" },
    { id: "inv-6", name: "Maize Seed (Obatanpa)", category: "seed", quantity: 40, unit: "kg", reorderLevel: 60, unitCost: 18, supplier: "SeedCo" },
  ],
  transactions: [
    { id: "tx-1", type: "income", category: "Crop Sales", description: "Oil palm FFB to GOPDC", amount: 84000, date: "2026-05-18", farmId: "farm-1" },
    { id: "tx-2", type: "expense", category: "Labor", description: "May payroll", amount: 32500, date: "2026-05-31", farmId: "farm-1" },
    { id: "tx-3", type: "expense", category: "Inputs", description: "Fertilizer restock", amount: 9600, date: "2026-05-10", farmId: "farm-2" },
    { id: "tx-4", type: "income", category: "Crop Sales", description: "Maize forward contract deposit", amount: 21000, date: "2026-06-02", farmId: "farm-2" },
    { id: "tx-5", type: "expense", category: "Logistics", description: "Haulage to Tema port", amount: 7400, date: "2026-06-08", farmId: "farm-1" },
    { id: "tx-6", type: "income", category: "Crop Sales", description: "Shallot early harvest", amount: 15200, date: "2026-06-15", farmId: "farm-3" },
  ],
  sales: [
    { id: "sale-1", cropName: "Oil Palm (FFB)", buyer: "GOPDC", destination: "Kwae Mill", quantityTons: 320, pricePerTon: 1050, date: "2026-05-18", status: "paid" },
    { id: "sale-2", cropName: "Cocoa", buyer: "Licensed Buying Co.", destination: "Takoradi Port", quantityTons: 42, pricePerTon: 18500, date: "2026-04-30", status: "delivered" },
    { id: "sale-3", cropName: "Maize", buyer: "Premium Foods", destination: "Kumasi", quantityTons: 60, pricePerTon: 2400, date: "2026-06-02", status: "shipped" },
    { id: "sale-4", cropName: "Shallots", buyer: "Makola Aggregators", destination: "Accra", quantityTons: 18, pricePerTon: 3100, date: "2026-06-15", status: "pending" },
  ],
  yields: [
    { id: "yld-1", cropName: "Oil Palm", farmId: "farm-1", harvestDate: "2025-12-15", expectedTons: 1380, actualTons: 1422 },
    { id: "yld-2", cropName: "Cocoa", farmId: "farm-1", harvestDate: "2025-10-20", expectedTons: 72, actualTons: 65 },
    { id: "yld-3", cropName: "Maize", farmId: "farm-2", harvestDate: "2025-08-12", expectedTons: 200, actualTons: 188 },
    { id: "yld-4", cropName: "Cassava", farmId: "farm-2", harvestDate: "2025-11-05", expectedTons: 510, actualTons: 533 },
  ],
};
